<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[The Program Started in ChromeTest]]>
    </line>
    <line>
      <![CDATA[The Execution Started in ValidateTC]]>
    </line>
    <line>
      <![CDATA[The Execution Failed in ValidateTC]]>
    </line>
    <line>
      <![CDATA[The Program Finished in ChromeTest]]>
    </line>
    <line>
      <![CDATA[The Program Started in FirefoxTest]]>
    </line>
    <line>
      <![CDATA[The Execution Started in ValidateTC]]>
    </line>
    <line>
      <![CDATA[The Execution Failed in ValidateTC]]>
    </line>
  </reporter-output>
  <suite started-at="2022-08-09T00:01:59 IST" name="Suite" finished-at="2022-08-09T00:02:28 IST" duration-ms="28117">
    <groups>
    </groups>
    <test started-at="2022-08-09T00:01:59 IST" name="ChromeTest" finished-at="2022-08-09T00:02:09 IST" duration-ms="9686">
      <class name="Test_Package.Listener_with_PropertyFile">
        <test-method is-config="true" signature="beforeClass(java.lang.String)[pri:0, instance:Test_Package.Listener_with_PropertyFile@d9345cd]" started-at="2022-08-09T00:01:59 IST" name="beforeClass" finished-at="2022-08-09T00:02:07 IST" duration-ms="7318" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Test_Package.Listener_with_PropertyFile@d9345cd]" started-at="2022-08-09T00:02:07 IST" name="beforeMethod" finished-at="2022-08-09T00:02:07 IST" duration-ms="469" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="ValidateTC()[pri:0, instance:Test_Package.Listener_with_PropertyFile@d9345cd]" started-at="2022-08-09T00:02:07 IST" name="ValidateTC" finished-at="2022-08-09T00:02:08 IST" duration-ms="1046" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[TC is Failed due to actual User Id is not matching with expected UserID did not expect [CPN469] but found [CPN469]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: TC is Failed due to actual User Id is not matching with expected UserID did not expect [CPN469] but found [CPN469]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at Test_Package.Listener_with_PropertyFile.ValidateTC(Listener_with_PropertyFile.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[The Execution Started in ValidateTC]]>
            </line>
            <line>
              <![CDATA[The Execution Failed in ValidateTC]]>
            </line>
          </reporter-output>
        </test-method> <!-- ValidateTC -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:Test_Package.Listener_with_PropertyFile@d9345cd]" started-at="2022-08-09T00:02:09 IST" name="afterMethod" finished-at="2022-08-09T00:02:09 IST" duration-ms="437" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:Test_Package.Listener_with_PropertyFile@d9345cd]" started-at="2022-08-09T00:02:09 IST" name="afterClass" finished-at="2022-08-09T00:02:09 IST" duration-ms="152" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- Test_Package.Listener_with_PropertyFile -->
    </test> <!-- ChromeTest -->
    <test started-at="2022-08-09T00:02:09 IST" name="FirefoxTest" finished-at="2022-08-09T00:02:28 IST" duration-ms="18338">
      <class name="Test_Package.Listener_with_PropertyFile">
        <test-method is-config="true" signature="beforeClass(java.lang.String)[pri:0, instance:Test_Package.Listener_with_PropertyFile@13e344d]" started-at="2022-08-09T00:02:09 IST" name="beforeClass" finished-at="2022-08-09T00:02:21 IST" duration-ms="12178" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Test_Package.Listener_with_PropertyFile@13e344d]" started-at="2022-08-09T00:02:21 IST" name="beforeMethod" finished-at="2022-08-09T00:02:23 IST" duration-ms="1228" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="ValidateTC()[pri:0, instance:Test_Package.Listener_with_PropertyFile@13e344d]" started-at="2022-08-09T00:02:23 IST" name="ValidateTC" finished-at="2022-08-09T00:02:23 IST" duration-ms="168" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[TC is Failed due to actual User Id is not matching with expected UserID did not expect [CPN469] but found [CPN469]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: TC is Failed due to actual User Id is not matching with expected UserID did not expect [CPN469] but found [CPN469]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at Test_Package.Listener_with_PropertyFile.ValidateTC(Listener_with_PropertyFile.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[The Execution Started in ValidateTC]]>
            </line>
            <line>
              <![CDATA[The Execution Failed in ValidateTC]]>
            </line>
          </reporter-output>
        </test-method> <!-- ValidateTC -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:Test_Package.Listener_with_PropertyFile@13e344d]" started-at="2022-08-09T00:02:23 IST" name="afterMethod" finished-at="2022-08-09T00:02:24 IST" duration-ms="597" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:Test_Package.Listener_with_PropertyFile@13e344d]" started-at="2022-08-09T00:02:24 IST" name="afterClass" finished-at="2022-08-09T00:02:28 IST" duration-ms="4029" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- Test_Package.Listener_with_PropertyFile -->
    </test> <!-- FirefoxTest -->
  </suite> <!-- Suite -->
</testng-results>
